const english = {
  username: 'Username',
  email: 'Email',
  first_name: 'First name',
  last_name: 'Last name',
  account_type: 'Account status',
  password: 'Password',
  repeat_password: 'Repeat password',
  new_password: 'New Password',
  edit: 'Edit',
  cancel: 'Cancel',
  save: 'Save',
  logout: 'Logout',
  delete_account: 'Delete account',
  successfully_updated: 'Successfully updated',
  successfully_deleted: 'Successfully deleted',
  successfully_added:   'Successfully added',
  something_went_wrong: 'Something went wrong',
  error: 'Error',
  malformed_json: 'Malformed JSON',
  close: 'Close',
  invalidate: 'Invalidate',
  metadata: 'Metadata',
  creation_date: 'Creation date',
  modification_date: 'Modification date',
  id: 'ID',
  copy: 'copy',
  copied: 'copied',
  refresh: 'refresh',
  infinite: 'infinite',
  usages_left: 'usages left',
  usage_count: 'usage count',
  register_token: 'Register Token',
  reusable: 'reusable',
  not_reusable: 'not reusable',
  expire_at: 'expire at',
  seconds: 'seconds',
  add: 'Add',
  delete: 'Delete',
  clear: 'Clear',
  your_devices: 'Your Devices',
  revoke_current_device: 'Do you really want to log out this device?',
  logout_everywhere_notice: 'Do you really want to log out every devices? If yes, also this device?',
  logout_everywhere_inclusive: 'Yes, also this device',
  logout_everywhere_exclusive: 'No, not this device',
  logout_everywhere_count: 'Logged out $$ devices',
  logout_everywhere: 'Log out everywhere',
  logged_out_devices: 'Logged out devices',
  this_device: 'this device',
}

export default english
