const german = {
  username: 'Username',
  email: 'E-Mail',
  first_name: 'Vorname',
  last_name: 'Nachname',
  account_type: 'Account Status',
  password: 'Passwort',
  repeat_password: 'Passwort wiederholen',
  new_password: 'Neues Passwort',
  edit: 'Bearbeiten',
  cancel: 'Abbrechen',
  save: 'Speichern',
  logout: 'Ausloggen',
  delete_account: 'Account löschen',
  successfully_updated: 'Erfolgreich aktualisiert',
  successfully_deleted: 'Erfolgreich gelöscht',
  successfully_added:   'Erfolgreich hinzugefügt',
  something_went_wrong: 'Etwas ist fehlgeschlagen',
  error: 'Fehler',
  malformed_json: 'Invalides JSON',
  close: 'Schließen',
  invalidate: 'Invalidieren',
  metadata: 'Metadaten',
  creation_date: 'Erstellungsdatum',
  modification_date: 'Veränderungsdatum',
  id: 'ID',
  copy: 'kopieren',
  copied: 'kopiert',
  refresh: 'aktualisieren',
  infinite: 'unendlich',
  usages_left: 'Benutzungen verfügbar',
  usage_count: 'Anzahl Benutzungen',
  register_token: 'Register Token',
  resusable: 'wiederverwendbar',
  not_reusable: 'nicht wiederverwendbar',
  expire_at: '',
  seconds: 'Sekunden',
  add: 'Hinzufügen',
  delete: 'Löschen',
  clear: 'Löschen / Zurücksetzen'
}

export default german
